package org.gensparql.core.model;

/**
 * Source type for typed solution mappings in GenSPARQL.
 *
 * According to the paper: μ : V → T × ζ, where ζ = {rdf, gen}
 * - RDF: values derived from standard SPARQL graph patterns (BGP)
 * - GEN: values generated by GenOp patterns (LLM outputs)
 */
public enum SourceType {
    /**
     * Value derived from RDF graph pattern (traditional SPARQL binding).
     */
    RDF,

    /**
     * Value generated by GenOp pattern (LLM-generated binding).
     */
    GEN
}
