package org.gensparql.example;

import org.apache.jena.query.*;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.sparql.algebra.Algebra;
import org.apache.jena.sparql.algebra.Op;
import org.apache.jena.util.FileManager;
import org.gensparql.engine.boot.GenSPARQL;
import org.gensparql.engine.exec.AlgebraGeneratorGenSPARQL;
import org.gensparql.parser.GenSPARQLQueryFactory;
import org.gensparql.parser.fmt.GenSPARQLFormatterElement;

import java.io.InputStream;

/**
 * Example 6: SimScore-based similarity join
 * 
 * Demonstrates semantic matching between RDF data and LLM-generated data.
 * 
 * This example shows:
 * 1. Querying scientist names from the database (RDF source)
 * 2. Using GENOP to generate descriptions (GEN source)
 * 3. Joining them using SimScore for semantic similarity matching
 * 
 * The SimScore join allows matching even when names are slightly different
 * (e.g., "Albert Einstein" from DB vs "Einstein" from LLM).
 * 
 * Key features:
 * - Uses threshold parameter in GENOP to control similarity matching
 * - Automatically uses similarity join when GEN variables are involved
 * - Supports both EmbeddingSimText and JaccardSimText strategies
 */
public class Query6Example {
    
    public static void main(String[] args) {
        // Initialize GenSPARQL
        GenSPARQL.init();
        
        // Optionally configure LLM provider
        // GenSPARQL.setDefaultProvider("openai");
        
        // Load the TTL data file
        String dataFile = "gensparql-example/data/scientists_awards.ttl";
        if (!java.nio.file.Files.exists(java.nio.file.Paths.get(dataFile))) {
            dataFile = "data/scientists_awards.ttl";
        }
        Model model = loadData(dataFile);
        
        // Execute query
        System.out.println("=== Query 6: SimScore-based Similarity Join ===");
        System.out.println("This query demonstrates semantic matching between:");
        System.out.println("  - RDF data: Scientist names from database");
        System.out.println("  - GEN data: Descriptions generated by LLM");
        System.out.println("  - Join: Uses SimScore for similarity matching\n");
        executeQuery(model);
    }
    
    private static Model loadData(String filename) {
        Model model = ModelFactory.createDefaultModel();
        InputStream in = FileManager.get().open(filename);
        if (in == null) {
            throw new IllegalArgumentException("File not found: " + filename);
        }
        model.read(in, null, "TTL");
        return model;
    }
    
    private static void executeQuery(Model model) {
        String queryString = readQueryFromFile("gensparql-example/queries/query6_simscore_join.sparql");
        if (queryString == null) {
            queryString = readQueryFromFile("queries/query6_simscore_join.sparql");
        }
        
        Query query = GenSPARQLQueryFactory.create(queryString);
        
        // Print query string
        System.out.println("--- Query String ---");
        System.out.println(queryString);
        
        // Print algebra tree
        System.out.println("\n--- Algebra Tree (Op Tree) ---");
        System.out.println("Note: Look for OpJoin operations that will use SimScore");
        Op op;
        try {
            // Try GenSPARQL algebra generator first (for queries with GENOP)
            op = AlgebraGeneratorGenSPARQL.compile(query.getQueryPattern());
            // Apply query modifiers (PROJECT, etc.)
            if (query.isSelectType() && query.getProjectVars() != null) {
                op = new org.apache.jena.sparql.algebra.op.OpProject(op, query.getProjectVars());
            }
        } catch (Exception e) {
            // Fallback to standard algebra
            op = Algebra.compile(query);
        }
        System.out.println(op.toString());
        
        // Print query pattern (using custom formatter for GENOP support)
        System.out.println("\n--- Query Pattern (Element Tree) ---");
        System.out.println(GenSPARQLFormatterElement.asString(query.getQueryPattern()));
        
        // Execute query
        System.out.println("\n--- Query Results ---");
        System.out.println("The join between ?scientist (RDF) and GENOP output will use SimScore");
        System.out.println("for semantic similarity matching.\n");
        try (QueryExecution qexec = QueryExecutionFactory.create(query, model)) {
            ResultSet results = qexec.execSelect();
            ResultSetFormatter.out(System.out, results, query);
        } catch (Exception e) {
            System.err.println("Error executing query: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    private static String readQueryFromFile(String filename) {
        try {
            java.nio.file.Path filePath = java.nio.file.Paths.get(filename);
            if (java.nio.file.Files.exists(filePath)) {
                return java.nio.file.Files.readString(filePath, java.nio.charset.StandardCharsets.UTF_8);
            }
            InputStream in = FileManager.get().open(filename);
            if (in != null) {
                try (in) {
                    return new String(in.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8);
                }
            }
            return null;
        } catch (Exception e) {
            return null;
        }
    }
}

